config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  scope(path_names: { new: 'novo', edit: 'editar' }) do
    devise_for :users, path: 'usuarios'
    resources :users, path: 'usuarios'
    resources :equivalences, path: 'equivalencias'
    resources :presences, path: "presenças"
    resources :subscriptions, path: "inscriçoes"
    resources :lessons, path: "aulas"
    resources :students, path: "alunos"
    resources :classrooms, path: "turmas"
    resources :periods, path: "periodos"
    resources :subjects, path: "materias"
    resources :courses, path: "cursos"
    resources :professors, path: "professores"
    resources :departments, path: "departamentos"
    resources :course_subjects, path: "materias_do_curso"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user
      can [:edit, :destroy, :show], User, id: user.id
      cannot :index, User
      if user.standard?
        can [:index, :show], [Course, Department]
      elsif user.admin?
        can :manage, :all
      elsif user.professor?
        can [:read], Professor
        can [:create, :index, :show], Classroom  
        can [:edit, :destroy], Classroom, professor_id: Professor.find_by(email: user.email).id
        can [:create, :index, :show], Lesson  
      elsif user.principal?
        can :manage, [Classroom, Professor, Lesson, Courses, Department, Subject]
      elsif user.coordinator?
        can :manage, [Classroom, Professor, Lesson, Subject]
      end
    else
      can [:index, :show], [Course, Department, Subject, Professor, Period]
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :professor
  belongs_to :subject
  belongs_to :period
  has_many :lessons
  has_many :subscriptions
  has_many :students , through: :subscriptions
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :students
  has_many :course_subjects
  has_many :subjects, through: :course_subjects
end

app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course
  belongs_to :subject
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :subjects
    has_many :professors 
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :subject
  belongs_to :equivalent_subject, class_name: "Subject"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom
  has_many :presences
  has_many :students, through: :presences
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :student
  belongs_to :lesson
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  belongs_to :user, optional: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :courses
  has_many :subscriptions
  has_many :classrooms , through: :subscriptions
  has_many :presences
  has_many :lessons, through: :presences
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department, optional: true
  has_many :course_subjects
  has_many :courses, through: :course_subjects
  has_many :equivalences
  has_many :equivalent_subjects, through: :equivalences, source: :equivalent_subject
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :student
  belongs_to :classroom
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :professor
  mount_uploader :photo, PhotosUploader
  validates :name, presence: true
  enum kind: {
    standard: 0,
    admin: 1,
    professor: 2,
    principal: 3,
    coordinator: 4
    
  }
end

app/controllers/equivalences_controller.rb
class EquivalencesController < ApplicationController
  before_action :set_equivalence, only: [:show, :edit, :update, :destroy]

  # GET /equivalences
  # GET /equivalences.json
  def index
    @equivalences = Equivalence.all
  end

  # GET /equivalences/1
  # GET /equivalences/1.json
  def show
  end

  # GET /equivalences/new
  def new
    @equivalence = Equivalence.new
  end

  # GET /equivalences/1/edit
  def edit
  end

  # POST /equivalences
  # POST /equivalences.json
  def create

    @equivalence = Equivalence.new(equivalence_params)

    respond_to do |format|
      if @equivalence.save
        format.html { redirect_to request.referrer, notice: 'Equivalence was successfully created.' }
        format.json { render request.referrer, status: :created, location: @equivalence }
      else
        format.html { render :new }
        format.json { render json: @equivalence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equivalences/1
  # PATCH/PUT /equivalences/1.json
  def update
    respond_to do |format|
      if @equivalence.update(equivalence_params)
        format.html { redirect_to @equivalence, notice: 'Equivalence was successfully updated.' }
        format.json { render :show, status: :ok, location: @equivalence }
      else
        format.html { render root_path }
        format.json { render json: @equivalence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equivalences/1
  # DELETE /equivalences/1.json
  def destroy
    @equivalence.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Equivalence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equivalence
      @equivalence = Equivalence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equivalence_params
      params.require(:equivalence).permit(:subject_id, :equivalent_subject_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/equivalences_helper.rb
module EquivalencesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def kind_options
        [["Professor", :professor], ["Diretor", :principal], ["Coordenador", :coordinator]]
    end
end

app/views/equivalences/_form.html.erb
<%= form_with(model: equivalence, local: true) do |form| %>
  <% if equivalence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equivalence.errors.count, "error") %> prohibited this equivalence from being saved:</h2>

      <ul>
      <% equivalence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field(:subject_id, :value => @subject.id )%>
  </div>

  <div class="field">
    <%= form.label :equivalent_subject_id %>
    <%= form.collection_select(:equivalent_subject_id, Subject.all, :id, :name, { :prompt => 'Escolha uma materia equivalente', :selected => equivalence.equivalent_subject_id }, { class: 'form-control' }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/equivalences/edit.html.erb
<h1>Editing Equivalence</h1>

<%= render 'form', equivalence: @equivalence %>

<%= link_to 'Show', @equivalence %> |
<%= link_to 'Back', equivalences_path %>

app/views/equivalences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equivalences</h1>

<table>
  <thead>
    <tr>
      <th>Subjects</th>
      <th>Equivalent subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equivalences.each do |equivalence| %>
      <tr>
        <td><%= equivalence.subjects %></td>
        <td><%= equivalence.equivalent_subject %></td>
        <td><%= link_to 'Show', equivalence %></td>
        <td><%= link_to 'Edit', edit_equivalence_path(equivalence) %></td>
        <td><%= link_to 'Destroy', equivalence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equivalence', new_equivalence_path %>

app/views/equivalences/new.html.erb
<h1>New Equivalence</h1>

<%= render 'form', equivalence: @equivalence %>

<%= link_to 'Back', equivalences_path %>

app/views/equivalences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subjects:</strong>
  <%= @equivalence.subjects %>
</p>

<p>
  <strong>Equivalent subject:</strong>
  <%= @equivalence.equivalent_subject %>
</p>

<%= link_to 'Edit', edit_equivalence_path(@equivalence) %> |
<%= link_to 'Back', equivalences_path %>